version: '3'

services:
  profile:
    container_name: profile-service
    build:
      context: .
      dockerfile: ./apps/profile-service/Dockerfile
    env_file:
      - apps/profile-service/.env
    ports:
      - 5000:5000
    command: npm run start:dev profile-service
    depends_on:
      - auth
      - profile-db
      - rabbitmq
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
  auth:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    env_file:
      - apps/auth-service/.env
    ports:
      - 5001:5000
    command: npm run start:dev auth-service
    depends_on:
      - auth-db
      - rabbitmq
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
  film:
    container_name: film-service
    build:
      context: .
      dockerfile: ./apps/films/Dockerfile
    env_file:
      - apps/films/.env
    ports:
      - 5002:5000
    command: npm run start:dev films
    depends_on:
      - film-db
      - rabbitmq
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
  person:
    container_name: person-service
    build:
      context: .
      dockerfile: ./apps/persons/Dockerfile
    env_file:
      - apps/persons/.env
    ports:
      - 5003:5000
    command: npm run start:dev persons
    depends_on:
      - person-db
      - rabbitmq
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
  auth-db:
    container_name: auth-db
    image: postgres:12
    env_file:
      - auth-db/.auth.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5434:5432
    volumes:
      - authdb:/var/lib/postgresql/data
      - ./auth-db:/var/lib/postgresql/pgdata
  profile-db:
    container_name: profile-db
    image: postgres:12
    env_file:
      - profile-db/.profile.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - profiledb:/var/lib/postgresql/data
      - ./profile-db:/var/lib/postgresql/pgdata
  film-db:
    container_name: film-db
    image: postgres:12
    env_file:
      - film-db/.film.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5435:5432
    volumes:
      - filmdb:/var/lib/postgresql/data
      - ./film-db:/var/lib/postgresql/pgdata
  person-db:
    container_name: person-db
    image: postgres:12
    env_file:
      - person-db/.person.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5436:5432
    volumes:
      - persondb:/var/lib/postgresql/data
      - ./person-db:/var/lib/postgresql/pgdata
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  authdb:
  profiledb:
  filmdb:
  persondb: